
project_id = "qjczhbllpzkkstustvbn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[[functions.analyze-writing-style]]
verify_jwt = true

[[functions.detect-ai-content]]
verify_jwt = true

[[functions.paraphrase-content]]
verify_jwt = true

[[functions.search-sources]]
verify_jwt = true

[[functions.semantic-plagiarism-check]]
verify_jwt = true

[[functions.semantic-search]]
verify_jwt = true

[[functions.batch-process-files]]
verify_jwt = true

[[functions.multilingual-plagiarism-check]]
verify_jwt = true
