
import { PlagiarismReport } from "@/hooks/use-plagiarism-reports";

export const downloadReport = (report: PlagiarismReport) => {
  const reportText = `
Plagiarism Analysis Report
=========================

Report Title: ${report.title}
Date: ${new Date(report.created_at).toLocaleString()}
Similarity Score: ${report.score}%
Word Count: ${report.word_count}
Status: ${report.status}

Analyzed Content:
${report.content}

Generated by Plagiarism Checker
`;
  
  const blob = new Blob([reportText], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${report.title.replace(/\s+/g, '-')}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
